#!/usr/bin/env bash
#
# Scaffold the repository structure for cloudrail-system.
# Creates all required directories and empty files using mkdir -p and touch.
# Safe to re-run; existing files/directories are left untouched.
#

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
cd "$REPO_ROOT"

declare -a DIRECTORIES=(
	"custom_skills/arch-baseline/scripts"
	"custom_skills/arch-baseline/resources/templates/baseline"
	"custom_skills/arch-baseline/resources/schemas"
	"custom_skills/arch-baseline/resources/policy"
	"custom_skills/arch-docs/scripts"
	"custom_skills/arch-docs/resources/templates/rfc"
	"custom_skills/arch-docs/resources/templates/adr"
	"custom_skills/arch-docs/resources/templates/c4"
	"custom_skills/arch-docs/resources/templates/security"
	"custom_skills/arch-docs/resources/templates/ops"
	"custom_skills/arch-docs/resources/templates/service"
	"custom_skills/arch-docs/resources/schemas"
	"custom_skills/arch-docs/resources/policy"
	"custom_skills/impl-strategy/scripts"
	"custom_skills/impl-strategy/resources/templates"
	"custom_skills/impl-strategy/resources/schemas"
	"custom_skills/impl-strategy/resources/policy"
	"docs/baseline"
	"docs/architecture"
	"docs/implementation"
	"docs/audit"
	"registries"
	"tools"
	".github/workflows"
)

for dir in "${DIRECTORIES[@]}"; do
	mkdir -p "$dir"
done

declare -a FILES=(
	"custom_skills/arch-baseline/SKILL.md"
	"custom_skills/arch-baseline/REFERENCE.md"
	"custom_skills/arch-baseline/EXAMPLES.md"
	"custom_skills/arch-baseline/TROUBLESHOOTING.md"
	"custom_skills/arch-baseline/scripts/scaffold_baseline.py"
	"custom_skills/arch-baseline/scripts/validate_baseline.py"
	"custom_skills/arch-baseline/scripts/validate_well_architected.py"
	"custom_skills/arch-baseline/scripts/utils_frontmatter.py"
	"custom_skills/arch-baseline/resources/templates/baseline/SYSTEM_CHARTER.md"
	"custom_skills/arch-baseline/resources/templates/baseline/SCOPE_BOUNDARIES.md"
	"custom_skills/arch-baseline/resources/templates/baseline/CLOUD_PROVIDER_DECISION_ADR.md"
	"custom_skills/arch-baseline/resources/templates/baseline/PROVIDER_COMPARISON_RFC.md"
	"custom_skills/arch-baseline/resources/templates/baseline/C4_Context.md"
	"custom_skills/arch-baseline/resources/templates/baseline/C4_Container.md"
	"custom_skills/arch-baseline/resources/templates/baseline/WELL_ARCHITECTED_ADHERENCE_PLAN.md"
	"custom_skills/arch-baseline/resources/schemas/baseline_manifest.schema.json"
	"custom_skills/arch-baseline/resources/schemas/doc_frontmatter.schema.json"
	"custom_skills/arch-baseline/resources/schemas/well_architected_adherence_plan.schema.json"
	"custom_skills/arch-baseline/resources/policy/required_sections.yml"
	"custom_skills/arch-baseline/resources/policy/baseline_gate.yml"
	"custom_skills/arch-baseline/resources/policy/provider_pillars.yml"
	"custom_skills/arch-docs/SKILL.md"
	"custom_skills/arch-docs/REFERENCE.md"
	"custom_skills/arch-docs/EXAMPLES.md"
	"custom_skills/arch-docs/TROUBLESHOOTING.md"
	"custom_skills/arch-docs/scripts/scaffold_docs.py"
	"custom_skills/arch-docs/scripts/validate_docs.py"
	"custom_skills/arch-docs/scripts/update_indexes.py"
	"custom_skills/arch-docs/scripts/emit_audit_bundle.py"
	"custom_skills/arch-docs/scripts/utils_frontmatter.py"
	"custom_skills/arch-docs/resources/templates/rfc/RFC.md"
	"custom_skills/arch-docs/resources/templates/adr/ADR.md"
	"custom_skills/arch-docs/resources/templates/c4/C4_Component.md"
	"custom_skills/arch-docs/resources/templates/c4/DIAGRAM_GUIDE.md"
	"custom_skills/arch-docs/resources/templates/security/THREAT_MODEL.md"
	"custom_skills/arch-docs/resources/templates/ops/RUNBOOK.md"
	"custom_skills/arch-docs/resources/templates/service/SERVICE_SPEC.md"
	"custom_skills/arch-docs/resources/schemas/doc_manifest.schema.json"
	"custom_skills/arch-docs/resources/schemas/claim_index.schema.json"
	"custom_skills/arch-docs/resources/schemas/audit_bundle.schema.json"
	"custom_skills/arch-docs/resources/policy/required_sections.yml"
	"custom_skills/arch-docs/resources/policy/crosslink_rules.yml"
	"custom_skills/arch-docs/resources/policy/placeholder_rules.yml"
	"custom_skills/impl-strategy/SKILL.md"
	"custom_skills/impl-strategy/REFERENCE.md"
	"custom_skills/impl-strategy/EXAMPLES.md"
	"custom_skills/impl-strategy/TROUBLESHOOTING.md"
	"custom_skills/impl-strategy/scripts/decompose_phases.py"
	"custom_skills/impl-strategy/scripts/build_task_graph.py"
	"custom_skills/impl-strategy/scripts/validate_task_graph.py"
	"custom_skills/impl-strategy/scripts/plan_worktrees.py"
	"custom_skills/impl-strategy/scripts/create_worktrees.sh"
	"custom_skills/impl-strategy/scripts/update_task_status.py"
	"custom_skills/impl-strategy/scripts/emit_delivery_bundle.py"
	"custom_skills/impl-strategy/resources/templates/IMPLEMENTATION_MASTER_PLAN.md"
	"custom_skills/impl-strategy/resources/templates/PHASE_PLAN.md"
	"custom_skills/impl-strategy/resources/templates/TASK.md"
	"custom_skills/impl-strategy/resources/templates/SUBTASK.md"
	"custom_skills/impl-strategy/resources/templates/GATE_CHECKLIST.md"
	"custom_skills/impl-strategy/resources/templates/PR_TEMPLATE.md"
	"custom_skills/impl-strategy/resources/schemas/task_graph.schema.json"
	"custom_skills/impl-strategy/resources/schemas/phase_plan.schema.json"
	"custom_skills/impl-strategy/resources/schemas/worktree_manifest.schema.json"
	"custom_skills/impl-strategy/resources/schemas/gate_results.schema.json"
	"custom_skills/impl-strategy/resources/policy/gate_definitions.yml"
	"custom_skills/impl-strategy/resources/policy/dependency_rules.yml"
	"custom_skills/impl-strategy/resources/policy/labeling_rules.yml"
	"custom_skills/impl-strategy/resources/policy/parallelization_heuristics.yml"
	"registries/constraints_registry.yml"
	"registries/service_catalog.yml"
	"registries/env_catalog.yml"
	"registries/event_catalog.yml"
	"registries/slo_catalog.yml"
	"registries/security_controls_catalog.yml"
	"tools/run_baseline_gate.sh"
	"tools/run_arch_docs_gate.sh"
	"tools/run_impl_gate.sh"
	".github/workflows/baseline-gate.yml"
	".github/workflows/arch-docs-gate.yml"
	".github/workflows/impl-strategy-gate.yml"
)

for file in "${FILES[@]}"; do
	touch "$file"
done

echo "Repository scaffold complete."
